baseURL = "https://nieshiming.cn"
title = "levi"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "levi"
description = "levi personal website"
keywords = "blog,developer,personal"
info = ["Keep your dream, And never give up"]
avatarURL = "images/avatar.jpg"
dateFormat = "2006-01-02"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'", "https://pic3.zhimg.com"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://cdn.jsdelivr.net/",
  "https://cdn.bootcss.com/",
  "https://fonts.googleapis.com/"
]
scriptsrc = ["'self'","https://unpkg.com", "https://cdn.bootcss.com/"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "ri-github-fill"
weight = 1
url = "https://github.com/nieshiming"

[[params.social]]
name = "知乎"
icon = "ri-zhihu-line"
weight = 2
url = "https://www.zhihu.com/people/xiang-zuo-zou-0o"

[[params.social]]
name = "掘金"
icon = "ri-radar-fill"
weight = 3
url = "https://juejin.cn/user/3597257776838583/posts"

[[params.social]]
name = "E-Maiil"
icon = "ri-mail-star-fill"
weight = 4
url = "mailto:nieshiming1219@163.com"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "首页"
weight = 1
url = "/"

[[languages.en.menu.main]]
name = "博客"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "标签"
weight = 3
url = "tags/"

[[languages.en.menu.main]]
name = "关于我"
weight = 4
url = "about/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4